"""
The interpreter for the Plymouth scripting language. It walks the AST
generated by the parser and executes it.
"""

from .tokenizer import Token
from .parser import *  # AST nodes
from .script_objects import *  # Runtime objects
from .lib_math import setup_math_library
from .lib_image import setup_image_library
from .lib_sprite import setup_sprite_library
from .lib_plymouth import setup_plymouth_library
from .lib_window import setup_window_library

class ReturnValue(Exception):
    """Custom exception used to unwind the stack for return statements."""
    def __init__(self, value):
        self.value = value

class Environment:
    """Manages variable scopes for the interpreter."""
    def __init__(self, enclosing=None):
        self.variables = {}
        self.enclosing = enclosing

    def define(self, name, value):
        self.variables[name] = value

    def get(self, name_token):
        name = name_token if isinstance(name_token, str) else name_token.value
        if name in self.variables:
            return self.variables[name]
        if self.enclosing is not None:
            return self.enclosing.get(name_token)
        raise NameError(f"Undefined variable '{name}'.")

    def assign(self, name_token, value):
        name = name_token if isinstance(name_token, str) else name_token.value
        if name in self.variables:
            self.variables[name] = value
            return value
        if self.enclosing is not None:
            return self.enclosing.assign(name_token, value)
        raise NameError(f"Undefined variable '{name}'.")

class Interpreter:
    """Walks the AST and executes the script."""
    def __init__(self, renderer=None):
        self.globals = Environment()
        self.environment = self.globals
        self.renderer = renderer

        # Callbacks
        self.refresh_callback = None
        self.display_normal_callback = None
        self.display_password_callback = None
        self.boot_progress_callback = None
        self.quit_callback = None
        self.display_message_callback = None
        self.hide_message_callback = None

        setup_math_library(self)
        # TODO: This should come from the .plymouth file
        image_dir = "themes/script"
        setup_image_library(self, image_dir)
        setup_sprite_library(self, self.renderer)
        setup_plymouth_library(self, self.renderer)
        setup_window_library(self, self.renderer)


    def tick(self):
        """Called by the renderer on every frame to run the refresh callback."""
        if self.refresh_callback:
            # logging.info("Interpreter tick") # This is too noisy
            self.execute_function(self.refresh_callback, [])

    def interpret(self, program_node):
        """Executes a program AST node."""
        last_value = Null()
        try:
            for statement in program_node.statements:
                last_value = self.visit(statement)
        except Exception as e:
            print(f"Runtime Error: {e}")
            return Null()
        return last_value

    def visit(self, node):
        method_name = f'visit_{type(node).__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node)

    def generic_visit(self, node):
        raise Exception(f'No visit_{type(node).__name__} method defined')

    def visit_Block(self, node, environment=None):
        if environment is None:
            environment = Environment(enclosing=self.environment)

        previous_env = self.environment
        self.environment = environment
        result = Null()
        try:
            for statement in node.statements:
                result = self.visit(statement)
        finally:
            self.environment = previous_env
        return result

    def visit_ExpressionStatement(self, node):
        return self.visit(node.expression)

    def visit_ReturnStatement(self, node):
        value = self.visit(node.value) if node.value else Null()
        raise ReturnValue(value)

    def visit_IfStatement(self, node):
        condition = self.visit(node.condition)
        # Check for truthiness
        if condition.value:
            return self.visit(node.then_branch)
        elif node.else_branch:
            return self.visit(node.else_branch)
        else:
            return Null()

    def visit_ForStatement(self, node):
        # Scoping for for loops can be tricky.
        # Let's assume for now it shares the current scope.
        self.visit(node.initializer)
        while True:
            condition = self.visit(node.condition)
            if not condition.value:
                break
            self.visit(node.body)
            self.visit(node.increment)
        return Null()

    def visit_Number(self, node): return Number(node.value)
    def visit_String(self, node): return String(node.value)
    def visit_Null(self, node): return Null()
    def visit_Boolean(self, node): return Boolean(node.value)

    def visit_LocalNode(self, node):
        return self.environment # Return the current local environment

    def visit_GlobalNode(self, node):
        return self.globals # Return the global environment

    def visit_Variable(self, node):
        return self.environment.get(node.name)

    def visit_Assignment(self, node):
        if not isinstance(node.left, (ast.Variable, ast.PropertyAccess, ast.IndexAccess)):
            raise TypeError("Invalid assignment target")

        # For compound assignments, we need the old value first
        if node.op.type != 'OP_ASSIGN':
            left_val = self.visit(node.left)
            right_val = self.visit(node.right)

            op_map = {
                'OP_ASSIGN_PLUS': '+',
                'OP_ASSIGN_MINUS': '-',
                'OP_ASSIGN_MUL': '*',
                'OP_ASSIGN_DIV': '/',
                'OP_ASSIGN_MOD': '%',
            }
            # Create a fake BinaryOp node to reuse the logic
            op_token = Token('OP_PLUS', op_map[node.op.type], 0, 0)
            bin_op_node = ast.BinaryOp(left_val, op_token, right_val)
            value_to_assign = self.visit(bin_op_node)
        else:
            value_to_assign = self.visit(node.right)

        # Now, perform the assignment
        if isinstance(node.left, ast.Variable):
            self.environment.define(node.left.name, value_to_assign)
        elif isinstance(node.left, ast.PropertyAccess):
            obj = self.visit(node.left.obj)
            if isinstance(obj, Hash):
                obj.set(node.left.property_name, value_to_assign)
            else:
                raise TypeError("Can only assign properties to hash objects.")
        elif isinstance(node.left, ast.IndexAccess):
            obj = self.visit(node.left.obj)
            index_obj = self.visit(node.left.index)
            if not isinstance(index_obj, Number):
                raise TypeError("Index must be a number.")
            index = int(index_obj.value)
            if isinstance(obj, ListObject):
                obj.set(index, value_to_assign)
            else:
                raise TypeError("Can only assign to indices of lists.")

        return value_to_assign

    def visit_FunctionDef(self, node):
        func_name = node.name
        closure = self.environment
        script_func = ScriptFunction(func_name, node.params, node.body, closure)
        if func_name:
            self.environment.define(func_name, script_func)
        return script_func

    def execute_function(self, callee, args):
        if isinstance(callee, Null):
            raise TypeError("Object NULL is not a function.")
        if not isinstance(callee, Function):
            raise TypeError(f"Object {callee} is not a function.")

        if isinstance(callee, NativeFunction):
            return callee(self, args)

        if isinstance(callee, ScriptFunction):
            call_env = Environment(enclosing=callee.closure)
            if len(args) != len(callee.params):
                raise TypeError(f"Function {callee.name} expects {len(callee.params)} arguments, but got {len(args)}.")

            for param_name, arg_value in zip(callee.params, args):
                call_env.define(param_name, arg_value)

            try:
                self.visit_Block(callee.body, call_env)
            except ReturnValue as ret:
                return ret.value

            return Null()

    def visit_FunctionCall(self, node):
        callee = self.visit(node.callee)
        args = [self.visit(arg) for arg in node.args]
        return self.execute_function(callee, args)

    def visit_PropertyAccess(self, node):
        obj = self.visit(node.obj)
        if isinstance(obj, Null):
            return Null() # Accessing a property of NULL returns NULL
        if not isinstance(obj, Hash):
            raise TypeError(f"Cannot access properties on non-hash object {obj}.")

        prop_name = node.property_name
        value = obj.get(prop_name)

        if value is None:
            return Null()

        return value

    def visit_IndexAccess(self, node):
        obj = self.visit(node.obj)
        index_obj = self.visit(node.index)

        if not isinstance(index_obj, Number):
            raise TypeError("Index must be a number.")

        index = int(index_obj.value)

        if isinstance(obj, ListObject):
            return obj.get(index)
        elif isinstance(obj, Hash):
            # Allow using hashes like associative arrays
            return obj.get(str(index)) # Or should we use the number? Let's use the number.
        else:
            raise TypeError("Object is not indexable.")

    def visit_BinaryOp(self, node):
        left = self.visit(node.left)
        right = self.visit(node.right)
        op = node.op.value

        # Note: This is a simplified implementation. A real one would have
        # more robust type checking and coercion rules.
        lval, rval = left.value, right.value

        if op == '+': return Number(lval + rval)
        if op == '-': return Number(lval - rval)
        if op == '*': return Number(lval * rval)
        if op == '/': return Number(lval / rval)
        if op == '%': return Number(lval % rval)
        if op == '>': return Boolean(lval > rval)
        if op == '>=': return Boolean(lval >= rval)
        if op == '<': return Boolean(lval < rval)
        if op == '<=': return Boolean(lval <= rval)
        if op == '==': return Boolean(lval == rval)
        if op == '!=': return Boolean(lval != rval)
        if op == '&&': return Boolean(lval and rval)
        if op == '||': return Boolean(lval or rval)

        raise Exception(f"Unsupported binary operator: {op}")

    def visit_UnaryOp(self, node):
        right = self.visit(node.right)
        op = node.op.value

        if op == '-':
            return Number(-right.value)
        if op == '!':
            is_truthy = not (isinstance(right, Null) or (isinstance(right, Boolean) and not right.value) or (isinstance(right, Number) and right.value == 0))
            return Boolean(not is_truthy)

        raise Exception(f"Unsupported unary operator: {op}")

    def visit_PostOp(self, node):
        # Postfix ops like i++ are tricky. They modify the variable
        # but evaluate to the *old* value.
        if not isinstance(node.left, ast.Variable):
            raise TypeError("Operand for ++/-- must be a variable.")

        var_name = node.left.name
        old_value = self.environment.get(var_name)

        if not isinstance(old_value, Number):
            raise TypeError("Operand for ++/-- must be a number.")

        if node.op.type == 'OP_INC':
            new_value = Number(old_value.value + 1)
        elif node.op.type == 'OP_DEC':
            new_value = Number(old_value.value - 1)
        else:
            raise Exception(f"Unsupported postfix operator: {node.op.type}")

        self.environment.assign(var_name, new_value)

        return old_value # Return the value *before* the increment/decrement
