"""
The interpreter for the Plymouth scripting language. It walks the AST
generated by the parser and executes it.
"""
import logging
from .tokenizer import Token
from .parser import *
from .script_objects import *
from .script_objects import Environment
from .lib_math import setup_math_library
from .lib_image import setup_image_library
from .lib_sprite import setup_sprite_library
from .lib_plymouth import setup_plymouth_library
from .lib_window import setup_window_library

logger = logging.getLogger(__name__)

class ReturnValue(Exception):
    def __init__(self, value):
        self.value = value

class Interpreter:
    def __init__(self, renderer=None):
        self.globals = Environment()
        self.environment = self.globals
        self.renderer = renderer
        self.refresh_callback = None
        self.display_normal_callback = None
        self.display_password_callback = None
        self.boot_progress_callback = None
        self.quit_callback = None
        self.display_message_callback = None
        self.hide_message_callback = None
        setup_math_library(self)
        image_dir = "themes/script"
        setup_image_library(self, image_dir)
        setup_sprite_library(self, self.renderer)
        setup_plymouth_library(self, self.renderer)
        setup_window_library(self, self.renderer)
        self.globals.define("logo", Hash())
        self.globals.define("dialog", Hash())
        self.globals.define("progress_box", Hash())
        self.globals.define("progress_bar", Hash())
        self.globals.define("message_sprite", Hash())

    def tick(self):
        if self.refresh_callback:
            self.execute_function(self.refresh_callback, [])

    def interpret(self, program_node):
        last_value = Null()
        try:
            for statement in program_node.statements:
                last_value = self.visit(statement)
        except Exception as e:
            logger.error(f"Runtime Error: {e}", exc_info=True)
            return Null()
        return last_value

    def interpret_in_thread(self, program_node):
        import threading
        interp_thread = threading.Thread(target=self.interpret, args=(program_node,))
        interp_thread.daemon = True
        interp_thread.start()

    def visit(self, node):
        method_name = f'visit_{type(node).__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node)

    def generic_visit(self, node):
        raise Exception(f'No visit_{type(node).__name__} method defined')

    def visit_Block(self, node, environment=None):
        if environment is None:
            environment = Environment(enclosing=self.environment)
        previous_env = self.environment
        self.environment = environment
        result = Null()
        try:
            for statement in node.statements:
                result = self.visit(statement)
        finally:
            self.environment = previous_env
        return result

    def visit_ExpressionStatement(self, node):
        return self.visit(node.expression)

    def visit_ReturnStatement(self, node):
        value = self.visit(node.value) if node.value else Null()
        raise ReturnValue(value)

    def visit_IfStatement(self, node):
        condition = self.visit(node.condition)
        if self._is_truthy(condition):
            return self.visit(node.then_branch)
        elif node.else_branch:
            return self.visit(node.else_branch)
        else:
            return Null()

    def visit_ForStatement(self, node):
        self.visit(node.initializer)
        while True:
            condition = self.visit(node.condition)
            if not self._is_truthy(condition):
                break
            self.visit(node.body)
            self.visit(node.increment)
        return Null()

    def visit_Number(self, node): return Number(node.value)
    def visit_String(self, node): return String(node.value)
    def visit_Null(self, node): return Null()
    def visit_Boolean(self, node): return Boolean(node.value)
    def visit_LocalNode(self, node): return self.environment
    def visit_GlobalNode(self, node): return self.globals

    def visit_Variable(self, node):
        return self.environment.get(node.name)

    def visit_Assignment(self, node):
        if not isinstance(node.left, (ast.Variable, ast.PropertyAccess, ast.IndexAccess)):
            raise TypeError("Invalid assignment target")
        if node.op.value != '=':
            left_val = self.visit(node.left)
            right_val = self.visit(node.right)
            op_map = {'+=': '+', '-=': '-', '*=': '*', '/=': '/', '%=': '%'}
            op_token = Token('OPERATOR', op_map[node.op.value], 0, 0)
            bin_op_node = ast.BinaryOp(left_val, op_token, right_val)
            value_to_assign = self.visit_BinaryOp(bin_op_node)
        else:
            value_to_assign = self.visit(node.right)
        if isinstance(node.left, ast.Variable):
            self.environment.define(node.left.name, value_to_assign)
        elif isinstance(node.left, ast.PropertyAccess):
            try:
                obj = self.visit(node.left.obj)
            except NameError:
                if isinstance(node.left.obj, ast.Variable):
                    obj = Hash()
                    self.environment.define(node.left.obj.name, obj)
                else:
                    raise
            if isinstance(obj, Hash):
                obj.set(node.left.property_name, value_to_assign)
            else:
                raise TypeError("Can only assign properties to hash objects.")
        elif isinstance(node.left, ast.IndexAccess):
            obj = self.visit(node.left.obj)
            index_obj = self.visit(node.left.index)
            if not isinstance(index_obj, Number):
                raise TypeError("Index must be a number.")
            index = int(index_obj.value)
            if isinstance(obj, ListObject):
                obj.set(index, value_to_assign)
            else:
                raise TypeError("Can only assign to indices of lists.")
        return value_to_assign

    def visit_FunctionDef(self, node):
        func_name = node.name
        closure = self.environment
        script_func = ScriptFunction(func_name, node.params, node.body, closure)
        if func_name:
            self.environment.define(func_name, script_func)
        return script_func

    def execute_function(self, callee, args):
        if isinstance(callee, Null):
            raise TypeError("Object NULL is not a function.")
        if isinstance(callee, ScriptFunction):
            logger.info(f"Calling script function '{callee.name}' with {len(args)} args.")
            call_env = Environment(enclosing=callee.closure)
            if len(args) != len(callee.params):
                raise TypeError(f"Function {callee.name} expects {len(callee.params)} arguments, but got {len(args)}.")
            for param_name, arg_value in zip(callee.params, args):
                call_env.define(param_name, arg_value)
            try:
                self.visit_Block(callee.body, call_env)
            except ReturnValue as ret:
                return ret.value
            return Null()
        if isinstance(callee, Function):
            return callee(self, args)
        raise TypeError(f"Object {callee} is not a function.")

    def visit_FunctionCall(self, node):
        callee = self.visit(node.callee)
        args = [self.visit(arg) for arg in node.args]
        return self.execute_function(callee, args)

    def visit_PropertyAccess(self, node):
        try:
            obj = self.visit(node.obj)
        except NameError:
            if isinstance(node.obj, ast.Variable):
                obj = Hash()
                self.environment.define(node.obj.name, obj)
            else:
                raise
        prop_name = node.property_name
        if isinstance(obj, Null):
            return Null()
        if isinstance(obj, ScriptObject) and hasattr(obj, 'get_method'):
            method = obj.get_method(prop_name)
            if method is not None and not isinstance(method, Null):
                return method
        if isinstance(obj, Hash):
            value = obj.get(prop_name)
            return value if value is not None else Null()
        if isinstance(obj, ScriptObject):
            value = obj.get(prop_name)
            return value if value is not None else Null()
        raise TypeError(f"Cannot access property '{prop_name}' on object of type {type(obj).__name__}.")

    def visit_IndexAccess(self, node):
        obj = self.visit(node.obj)
        index_obj = self.visit(node.index)
        if not isinstance(index_obj, Number):
            raise TypeError("Index must be a number.")
        index = int(index_obj.value)
        if isinstance(obj, ListObject):
            return obj.get(index)
        elif isinstance(obj, Hash):
            return obj.get(str(index))
        else:
            raise TypeError("Object is not indexable.")

    def _is_truthy(self, obj):
        if isinstance(obj, Null): return False
        if isinstance(obj, Boolean): return obj.value
        if isinstance(obj, Number): return obj.value != 0
        return True

    def visit_BinaryOp(self, node):
        op = node.op.value
        if op == '||':
            left = self.visit(node.left)
            if self._is_truthy(left):
                return left
            return self.visit(node.right)
        if op == '&&':
            left = self.visit(node.left)
            if not self._is_truthy(left):
                return left
            return self.visit(node.right)
        left = self.visit(node.left)
        right = self.visit(node.right)
        lval, rval = left.value, right.value
        if op == '+': return Number(lval + rval)
        if op == '-': return Number(lval - rval)
        if op == '*': return Number(lval * rval)
        if op == '/': return Number(lval / rval)
        if op == '%': return Number(lval % rval)
        if op == '>': return Boolean(lval > rval)
        if op == '>=': return Boolean(lval >= rval)
        if op == '<': return Boolean(lval < rval)
        if op == '<=': return Boolean(lval <= rval)
        if op == '==': return Boolean(lval == rval)
        if op == '!=': return Boolean(lval != rval)
        raise Exception(f"Unsupported binary operator: {op}")

    def visit_UnaryOp(self, node):
        right = self.visit(node.right)
        op = node.op.value
        if op == '-':
            return Number(-right.value)
        if op == '!':
            is_truthy = not self._is_truthy(right)
            return Boolean(is_truthy)
        raise Exception(f"Unsupported unary operator: {op}")

    def visit_PostOp(self, node):
        if not isinstance(node.left, ast.Variable):
            raise TypeError("Operand for ++/-- must be a variable.")
        var_name = node.left.name
        old_value = self.environment.get(var_name)
        if not isinstance(old_value, Number):
            raise TypeError("Operand for ++/-- must be a number.")
        if node.op.value == '++':
            new_value = Number(old_value.value + 1)
        elif node.op.value == '--':
            new_value = Number(old_value.value - 1)
        else:
            raise Exception(f"Unsupported postfix operator: {node.op.value}")
        self.environment.assign(var_name, new_value)
        return old_value
